name: boatmotion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  # opencv_4: ^5.3.0
  # opencv: ^4.7.0
  path_provider: ^2.1.1
  opencv_dart: ^1.4.3
  image_picker: ^1.2.0
  sensors_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
